(command "NETLOAD""C:/AUTOCAD-SETUP CG/CG_LISP/UTMCHECKCLOSE.dll")
(command "NETLOAD""C:/AUTOCAD-SETUP CG/CG_LISP/UTMSAVEAS.dll")
(command "NETLOAD""C:/AUTOCAD-SETUP CG/CG_LISP/SECTIONGENERATOR.dll")
